import{a as i,S as d,i as n}from"./assets/vendor-dNBuWDsd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();function f(l){i.defaults.baseURL="https://pixabay.com";const t=new URLSearchParams({key:"55116148-63b4b48da282efb6025f7a072",q:l,image_type:"photo",orientation:"horizontal",safesearch:!0});return i.get(`/api/?${t}`)}function m(l){const t=l.map(r=>`<div class="gallery-item">
        <a class="img-link" href="${r.webformatURL}"><img class="img" src="${r.largeImageURL}" alt="${r.tags}" width='360' height='156'>
        <ul class="img-descr">
    <li class="descr"><h2 class="title-descr">Likes</h2>  <p class="descr-text">${r.likes}</p></li>
      <li class="descr"><h2 class="title-descr">Views</h2>  <p class="descr-text">${r.views}</p></li>
      <li class="descr"><h2 class="title-descr">Comments</h2>  <p class="descr-text">${r.comments}</p></li>
      <li class="descr"><h2 class="title-descr">Downloads</h2> <p class="descr-text">${r.downloads}</p></li></ul>
    </ul></a>
        
    </div>`).join("");o.galleryEl.insertAdjacentHTML("beforeend",t),new d(".img-link")}function h(){return o.galleryEl.innerHTML=""}function p(){return o.loader.classList.add("loader")}function u(){return o.loader.classList.remove("loader")}new d(".img-link",{});const o={formEl:document.querySelector(".form"),inputEl:document.querySelector('input[name="search-text"]'),searchButtonEl:document.querySelector("button"),galleryEl:document.querySelector(".gallery"),loader:document.querySelector(".js-loader")};o.formEl.addEventListener("submit",y);function y(l){l.preventDefault(),h();const t=o.inputEl.value.trim();if(console.log(t),t===""){u(),n.show({color:"red",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(),f(t).then(r=>{m(r.data.hits)}).catch(r=>{n.show({message:"Error"}),console.log(r)}).finally(()=>{u()}),o.formEl.reset()}
//# sourceMappingURL=index.js.map
