import{a as i,S as d,i as n}from"./assets/vendor-dNBuWDsd.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function f(o){i.defaults.baseURL="https://pixabay.com";const r=new URLSearchParams({key:"55116148-63b4b48da282efb6025f7a072",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0});return i.get(`/api/?${r}`)}function m(o){const r=o.map(s=>`<div class="gallery-item">
        <a class="img-link" href="${s.webformatURL}"><img class="img" src="${s.largeImageURL}" alt="${s.tags}" width='360' height='156'>
        <ul class="img-descr">
    <li class="descr"><h2 class="title-descr">Likes</h2>  <p class="descr-text">${s.likes}</p></li>
      <li class="descr"><h2 class="title-descr">Views</h2>  <p class="descr-text">${s.views}</p></li>
      <li class="descr"><h2 class="title-descr">Comments</h2>  <p class="descr-text">${s.comments}</p></li>
      <li class="descr"><h2 class="title-descr">Downloads</h2> <p class="descr-text">${s.downloads}</p></li></ul>
    </ul></a>
        
    </div>`).join("");l.galleryEl.insertAdjacentHTML("beforeend",r),new d(".img-link").refresh()}function h(){return l.galleryEl.innerHTML=""}function p(){return l.loader.classList.add("loader")}function u(){return l.loader.classList.remove("loader")}new d(".img-link",{});const l={formEl:document.querySelector(".form"),inputEl:document.querySelector('input[name="search-text"]'),searchButtonEl:document.querySelector("button"),galleryEl:document.querySelector(".gallery"),loader:document.querySelector(".js-loader")};l.formEl.addEventListener("submit",y);function y(o){o.preventDefault(),h();const r=l.inputEl.value.trim();if(console.log(r),r===""){u(),n.show({color:"red",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(),f(r).then(a=>{m(a.data.hits)}).catch(a=>{n.show({message:"Error"}),console.log(a)}).finally(()=>{u()}),l.formEl.reset()}
//# sourceMappingURL=index.js.map
